# Combined Questionnaire & Syntaxes for all 5 indicators

Chapters 4 through 7, presented the questionnaires and syntax by indicator.  The resources below contain qeustions and syntax for all 5 food security direct evidence indicators as well as standardized geographic questions.

### Paper Version of Questionnaire

Here are the standardized modules in word format:

[RBDstandardized_questionnairecombined_EN](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/questionnaires/RBDstandardized_questionnairecombined_EN.docx?raw=true?raw=true) 

### Electronic Version of Questionnaire

Here are standardized modules in xlsform:

[RBDstandardized_questionnairecombined_EN](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/questionnaires/RBDstandardized_questionnairecombined_EN.xlsx?raw=true) 

### Example data set

Here is the example raw data set:

[exampledataEnglish_raw](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/example_datasets/exampledataEnglish_raw.sav?raw=true) 

### SPSS Syntax

Here is the combined SPSS syntax file for calculating the 5 indicators: 

[RBDstandardized_Rsyntaxcombined_EN](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/syntax/RBDstandardized_Rsyntaxcombined_EN.sps?raw=true) 

*Note - still looking for a way to create  ADMIN1Code & ADMIN2Code variables from the variables ADMIN1Name & ADMIN2Name in SPSS*


### R Syntax

Here is the combined R syntax file for calculating the 5 indicators: 

[RBDstandardized_Rsyntaxcombined_EN](https://github.com/WFP-VAM/RBD_FS_CH_guide_EN/blob/master/syntax/RBDstandardized_Rsyntaxcombined_EN.R?raw=true) 

*Note - R code above creates the variables ADMIN1Code & ADMIN2Code from the variables ADMIN1Name & ADMIN2Name*
